# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_auth_window(object):
    def setupUi(self, auth_window):
        auth_window.setObjectName("auth_window")
        auth_window.resize(402, 120)
        self.formLayoutWidget = QtWidgets.QWidget(auth_window)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 10, 341, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.loginEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.loginEntry.setObjectName("loginEntry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginEntry)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pswEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pswEntry.setObjectName("pswEntry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pswEntry)
        self.auth_reg_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.auth_reg_button.setObjectName("auth_reg_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.auth_reg_button)
        self.auth_entry_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.auth_entry_button.setObjectName("auth_entry_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.auth_entry_button)

        self.retranslateUi(auth_window)
        QtCore.QMetaObject.connectSlotsByName(auth_window)

    def retranslateUi(self, auth_window):
        _translate = QtCore.QCoreApplication.translate
        auth_window.setWindowTitle(_translate("auth_window", "Авторизация"))
        self.label.setText(_translate("auth_window", "Логин:"))
        self.label_2.setText(_translate("auth_window", "Пароль:"))
        self.auth_reg_button.setText(_translate("auth_window", "Зарегестрироваться"))
        self.auth_entry_button.setText(_translate("auth_window", "Войти"))



