# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(753, 392)
        self.exit_button = QtWidgets.QLabel(main_window)
        self.exit_button.setGeometry(QtCore.QRect(0, 0, 781, 441))
        self.exit_button.setText("")
        self.exit_button.setPixmap(QtGui.QPixmap("pictures/PAIN2.jpg"))
        self.exit_button.setObjectName("exit_button")
        self.employee_button = QtWidgets.QPushButton(main_window)
        self.employee_button.setGeometry(QtCore.QRect(420, 20, 271, 61))
        self.employee_button.setObjectName("employee_button")
        self.procedures_button = QtWidgets.QPushButton(main_window)
        self.procedures_button.setGeometry(QtCore.QRect(420, 90, 271, 61))
        self.procedures_button.setObjectName("procedures_button")
        self.clients_button = QtWidgets.QPushButton(main_window)
        self.clients_button.setGeometry(QtCore.QRect(420, 160, 271, 61))
        self.clients_button.setObjectName("clients_button")
        self.rooms_button = QtWidgets.QPushButton(main_window)
        self.rooms_button.setGeometry(QtCore.QRect(420, 230, 271, 61))
        self.rooms_button.setObjectName("rooms_button")
        self.rooms_button_2 = QtWidgets.QPushButton(main_window)
        self.rooms_button_2.setGeometry(QtCore.QRect(420, 300, 271, 61))
        self.rooms_button_2.setObjectName("rooms_button_2")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Санаторий"))
        self.employee_button.setText(_translate("main_window", "Сотрудники"))
        self.procedures_button.setText(_translate("main_window", "Процедуры"))
        self.clients_button.setText(_translate("main_window", "Клиенты"))
        self.rooms_button.setText(_translate("main_window", "Номера"))
        self.rooms_button_2.setText(_translate("main_window", "Выход из программы"))


