# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reg_window(object):
    def setupUi(self, reg_window):
        reg_window.setObjectName("reg_window")
        reg_window.resize(245, 179)
        self.label = QtWidgets.QLabel(reg_window)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.login_entry = QtWidgets.QLineEdit(reg_window)
        self.login_entry.setGeometry(QtCore.QRect(10, 40, 221, 20))
        self.login_entry.setObjectName("login_entry")
        self.label_2 = QtWidgets.QLabel(reg_window)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_2.setObjectName("label_2")
        self.psw_entry = QtWidgets.QLineEdit(reg_window)
        self.psw_entry.setGeometry(QtCore.QRect(10, 90, 221, 20))
        self.psw_entry.setObjectName("psw_entry")
        self.reg_button = QtWidgets.QPushButton(reg_window)
        self.reg_button.setGeometry(QtCore.QRect(10, 130, 131, 23))
        self.reg_button.setObjectName("reg_button")
        self.back_button = QtWidgets.QPushButton(reg_window)
        self.back_button.setGeometry(QtCore.QRect(150, 130, 75, 23))
        self.back_button.setObjectName("back_button")

        self.retranslateUi(reg_window)
        QtCore.QMetaObject.connectSlotsByName(reg_window)


    def retranslateUi(self, reg_window):
        _translate = QtCore.QCoreApplication.translate
        reg_window.setWindowTitle(_translate("reg_window", "Авторизация"))
        self.label.setText(_translate("reg_window", "Придумайте логин:"))
        self.label_2.setText(_translate("reg_window", "Придумайте пароль:"))
        self.reg_button.setText(_translate("reg_window", "Зарегестрироваться"))
        self.back_button.setText(_translate("reg_window", "Назад"))



